local lay = {
  LinearLayout;
  layout_height="8%h";
  layout_width="-1";
  {
    LinearLayout;
    gravity="center";
    layout_width="48dp";
    layout_height="fill";
    {
      ImageView;
      layout_height="fill";
      layout_width="26dp";
      src="src/image.png";
      id="icon";
    };
  };
  {
    LinearLayout;
    layout_gravity="center";
    layout_width="fill";
    gravity="left";
    layout_marginRight="4dp";
    orientation="vertical";
    {
      LinearLayout;
      layout_width="fill";
      {
        LinearLayout;
        {
          TextView;
          textColor="#616161";
          text="error";
          layout_width="56%w";
          singleLine=true;
          ellipsize="middle";
          layout_marginRight="10dp";
          textSize="16sp";
          id="filename";
        };
      };
      {
        LinearLayout;
        gravity="center";
        id="label";
      };
    };
    {
      LinearLayout;
      layout_width="fill";
      {
        TextView;
        layout_marginRight="8dp";
        text="error";
        textSize="14sp";
        textColor="#9E9E9E";
        id="info";
      };
      {
        ImageView;
        alpha="0.5";
        layout_gravity="center";
        src="src/eye.png";
      };
      {
        TextView;
        layout_marginRight="4dp";
        textColor="#9E9E9E";
        singleLine=true;
        ellipsize="end";
        text="error";
        id="views";
      };
      {
        ImageView;
        src="src/download.png";
        layout_gravity="center";
        alpha="0.5";
      };
      {
        TextView;
        text="error";
        textColor="#9E9E9E";
        singleLine=true;
        ellipsize="end";
        id="downs";
      };
    };
  };
};
return lay;